### PR TITLE
Compatible with UE5.6 UE5.7 and UE5.8

### PR DESCRIPTION
**Pull request by quicklyslow**
make the plugin compatible with UnrealEngine 5.6 and 5.7, and fix AddToRoot, will cause actor with this component can not be gc

### CODE REVIEW

**Comment by WANGHESI** [comment]
Can you help me to support Android

**Comment by JoseDVJ** [comment]
Hello quicklyslow, I'm Dauris. I want to ask you if the gfur plugin is updated for version 5.7 and if not, I would pay to update it to that version and maybe other updates.

**Comment by quicklyslow** [comment]
I had already updated for ue5.7 in this commit https://github.com/GiM-GamesInMotion/gFurPro/pull/48/commits/c8cc67440d250c3d9569b6177785adef2643591b
And is in sync in this pr

**Comment by jalakarp** [comment]
> I had already updated for ue5.7 in this commit [c8cc674](https://github.com/GiM-GamesInMotion/gFurPro/commit/c8cc67440d250c3d9569b6177785adef2643591b) And is in sync in this pr

Are you sure it is compatible with 5.7.3? Does not compile with 5.7 build tool


[1/8] Compile [x64] FurMorphObject.cpp
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurMorphObject.h(10,38): error C2504: 'FVertexBuffer': base class undefined
class FFurMorphVertexBuffer : public FVertexBuffer
                                     ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurMorphObject.h(43,15): error C2143: syntax error: missing ';' before '*'
        FVertexBuffer* GetVertexBuffer() { return &VertexBuffer; }
                     ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurMorphObject.h(43,15): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurMorphObject.h(43,35): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
        FVertexBuffer* GetVertexBuffer() { return &VertexBuffer; }
                                         ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurMorphObject.cpp(18,2): error C2065: 'VertexBufferRHI': undeclared identifier
        VertexBufferRHI = RHICmdList.CreateBuffer(CreateDesc);
        ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurMorphObject.cpp(31,43): error C2065: 'VertexBufferRHI': undeclared identifier
        void* BufferData = RHICmdList.LockBuffer(VertexBufferRHI, 0, Size, RLM_WriteOnly);
                                                 ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurMorphObject.cpp(35,26): error C2065: 'VertexBufferRHI': undeclared identifier
        RHICmdList.UnlockBuffer(VertexBufferRHI);
                                ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurMorphObject.cpp(40,2): error C2065: 'VertexBufferRHI': undeclared identifier
        VertexBufferRHI.SafeRelease();
        ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurMorphObject.cpp(48,2): error C2665: 'BeginInitResource': no overloaded function could convert all the argument types
        BeginInitResource(&VertexBuffer);
        ^
C:\UE_5.7\Engine\Source\Runtime\RenderCore\Public\RenderResource.h(218,28): note: could be 'void BeginInitResource(FRenderResource *,FRenderCommandPipe *)'
extern RENDERCORE_API void BeginInitResource(FRenderResource* Resource, FRenderCommandPipe* RenderCommandPipe = nullptr);
                           ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurMorphObject.cpp(48,2): note: 'void BeginInitResource(FRenderResource *,FRenderCommandPipe *)': cannot convert argument 1 from 'FFurMorphVertexBuffer *' to 'FRenderResource *'
        BeginInitResource(&VertexBuffer);
        ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurMorphObject.cpp(48,20): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
        BeginInitResource(&VertexBuffer);
                          ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurMorphObject.cpp(48,2): note: while trying to match the argument list '(FFurMorphVertexBuffer *)'
        BeginInitResource(&VertexBuffer);
        ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurMorphObject.cpp(53,19): error C2039: 'IsInitialized': is not a member of 'FFurMorphVertexBuffer'
        if (VertexBuffer.IsInitialized())
                         ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurMorphObject.h(10,7): note: see declaration of 'FFurMorphVertexBuffer'
class FFurMorphVertexBuffer : public FVertexBuffer
      ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurMorphObject.cpp(54,16): error C2039: 'ReleaseResource': is not a member of 'FFurMorphVertexBuffer'
                VertexBuffer.ReleaseResource();
                             ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurMorphObject.h(10,7): note: see declaration of 'FFurMorphVertexBuffer'
class FFurMorphVertexBuffer : public FVertexBuffer
      ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurMorphObject.cpp(149,22): error C2039: 'IsInitialized': is not a member of 'FFurMorphVertexBuffer'
                        if (!VertexBuffer.IsInitialized())
                                          ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurMorphObject.h(10,7): note: see declaration of 'FFurMorphVertexBuffer'
class FFurMorphVertexBuffer : public FVertexBuffer
      ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurMorphObject.cpp(152,18): error C2039: 'InitResource': is not a member of 'FFurMorphVertexBuffer'
                                VertexBuffer.InitResource(RHICmdList);
                                             ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurMorphObject.h(10,7): note: see declaration of 'FFurMorphVertexBuffer'
class FFurMorphVertexBuffer : public FVertexBuffer
      ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurMorphObject.cpp(162,97): error C2039: 'VertexBufferRHI': is not a member of 'FFurMorphVertexBuffer'
                        FMorphGPUSkinVertex* ActualBuffer = (FMorphGPUSkinVertex*)RHICmdList.LockBuffer(VertexBuffer.VertexBufferRHI, 0, Size * NumLayers, RLM_WriteOnly);
                                                                                                                     ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurMorphObject.h(10,7): note: see declaration of 'FFurMorphVertexBuffer'
class FFurMorphVertexBuffer : public FVertexBuffer
      ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurMorphObject.cpp(182,41): error C2039: 'VertexBufferRHI': is not a member of 'FFurMorphVertexBuffer'
                        RHICmdList.UnlockBuffer(VertexBuffer.VertexBufferRHI);
                                                             ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurMorphObject.h(10,7): note: see declaration of 'FFurMorphVertexBuffer'
class FFurMorphVertexBuffer : public FVertexBuffer
      ^
[2/8] Compile [x64] FurData.cpp
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurData.cpp(16,6): error C4668: 'ENGINE_MAJOR_VERSION' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
#if (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 6)
     ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurData.cpp(22,2): warning C4996: 'FRHIResourceCreateInfo': FRHIResourceCreateInfo is no longer used. Please use FRHIBufferCreateDesc or FRHITextureCreateDesc. - Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
        FRHIResourceCreateInfo CreateInfo(L"FurVertexBuffer");
        ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurData.cpp(22,35): warning C4996: 'FRHIResourceCreateInfo::FRHIResourceCreateInfo': FRHIResourceCreateInfo is no longer used. Please use FRHIBufferCreateDesc or FRHITextureCreateDesc. - Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
        FRHIResourceCreateInfo CreateInfo(L"FurVertexBuffer");
                                         ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurData.cpp(26,30): warning C4996: 'FRHICommandListBase::CreateVertexBuffer': CreateBuffer without FRHIBufferCreateDesc is deprecated - Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
        VertexBufferRHI = RHICmdList.CreateVertexBuffer(Size, BUF_Static, CreateInfo);
                                    ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurData.cpp(53,6): error C4668: 'ENGINE_MAJOR_VERSION' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
#if (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 6)
     ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurData.cpp(58,5): warning C4996: 'FRHIResourceCreateInfo': FRHIResourceCreateInfo is no longer used. Please use FRHIBufferCreateDesc or FRHITextureCreateDesc. - Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
                                FRHIResourceCreateInfo CreateInfo(L"FurVertexBuffer");
                                ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurData.cpp(58,38): warning C4996: 'FRHIResourceCreateInfo::FRHIResourceCreateInfo': FRHIResourceCreateInfo is no longer used. Please use FRHIBufferCreateDesc or FRHITextureCreateDesc. - Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
                                FRHIResourceCreateInfo CreateInfo(L"FurVertexBuffer");
                                                                 ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurData.cpp(60,33): warning C4996: 'FRHICommandListBase::CreateVertexBuffer': CreateBuffer without FRHIBufferCreateDesc is deprecated - Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
                                VertexBufferRHI = RHICmdList.CreateVertexBuffer(Size, BUF_Dynamic, CreateInfo);
                                                            ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurData.cpp(84,6): error C4668: 'ENGINE_MAJOR_VERSION' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
#if (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 6)
     ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurData.cpp(89,2): warning C4996: 'FRHIResourceCreateInfo': FRHIResourceCreateInfo is no longer used. Please use FRHIBufferCreateDesc or FRHITextureCreateDesc. - Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
        FRHIResourceCreateInfo CreateInfo(L"FurVertexBuffer");
        ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurData.cpp(89,35): warning C4996: 'FRHIResourceCreateInfo::FRHIResourceCreateInfo': FRHIResourceCreateInfo is no longer used. Please use FRHIBufferCreateDesc or FRHITextureCreateDesc. - Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
        FRHIResourceCreateInfo CreateInfo(L"FurVertexBuffer");
                                         ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurData.cpp(90,29): warning C4996: 'FRHICommandListBase::CreateIndexBuffer': CreateBuffer without FRHIBufferCreateDesc is deprecated - Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
        IndexBufferRHI = RHICmdList.CreateIndexBuffer(sizeof(int32), Indices.Num() * sizeof(int32), BUF_Static, CreateInfo);
                                   ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurData.cpp(98,9): warning C4996: 'TArray<int,FDefaultAllocator>::SetNum': SetNum with a boolean bAllowShrinking has been deprecated - please use the EAllowShrinking enum instead - Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
        Indices.SetNum(0, true);
               ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurData.cpp(118,6): error C4668: 'ENGINE_MAJOR_VERSION' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
#if (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 6)
     ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurData.cpp(122,5): warning C4996: 'FRHIResourceCreateInfo': FRHIResourceCreateInfo is no longer used. Please use FRHIBufferCreateDesc or FRHITextureCreateDesc. - Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
                                FRHIResourceCreateInfo CreateInfo(L"FurVertexBuffer");
                                ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurData.cpp(122,38): warning C4996: 'FRHIResourceCreateInfo::FRHIResourceCreateInfo': FRHIResourceCreateInfo is no longer used. Please use FRHIBufferCreateDesc or FRHITextureCreateDesc. - Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
                                FRHIResourceCreateInfo CreateInfo(L"FurVertexBuffer");
                                                                 ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurData.cpp(123,32): warning C4996: 'FRHICommandListBase::CreateIndexBuffer': CreateBuffer without FRHIBufferCreateDesc is deprecated - Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
                                IndexBufferRHI = RHICmdList.CreateIndexBuffer(sizeof(int32), Size, BUF_Dynamic, CreateInfo);
                                                           ^
[3/8] Compile [x64] FurSplines.cpp
[4/8] Compile [x64] FurComponent.cpp
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(123,51): error C2027: use of undefined type 'FSceneViewFamily'
                const bool Wireframe = AllowDebugViewmodes() && ViewFamily.EngineShowFlags.Wireframe;
                                                                ^
C:\UE_5.7\Engine\Source\Runtime\Engine\Public\SceneInterface.h(69,7): note: see declaration of 'FSceneViewFamily'
class FSceneViewFamily;
      ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(123,14): error C2737: 'Wireframe': const object must be initialized
                const bool Wireframe = AllowDebugViewmodes() && ViewFamily.EngineShowFlags.Wireframe;
                           ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(125,121): error C2027: use of undefined type 'UMaterial'
                FMaterialRenderProxy* WireframeMaterialInstance = new FColoredMaterialRenderProxy(GEngine->WireframeMaterial ? GEngine->WireframeMaterial->GetRenderProxy() : NULL, FLinearColor(0, 0.5f, 1.f));
                                                                                                                                      ^
C:\UE_5.7\Engine\Source\Runtime\Engine\Public\MaterialShared.h(68,7): note: see declaration of 'UMaterial'
class UMaterial;
      ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(125,142): error C2039: 'GetRenderProxy': is not a member of 'TObjectPtr<UMaterial>'
                FMaterialRenderProxy* WireframeMaterialInstance = new FColoredMaterialRenderProxy(GEngine->WireframeMaterial ? GEngine->WireframeMaterial->GetRenderProxy() : NULL, FLinearColor(0, 0.5f, 1.f));
                                                                                                                                                           ^
C:\UE_5.7\Engine\Source\Runtime\Engine\Classes\Engine\Engine.h(933,2): note: see declaration of 'TObjectPtr<UMaterial>'
        TObjectPtr<class UMaterial> WireframeMaterial;
        ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(125,84): error C2665: 'FColoredMaterialRenderProxy::FColoredMaterialRenderProxy': no overloaded function could convert all the argument types
                FMaterialRenderProxy* WireframeMaterialInstance = new FColoredMaterialRenderProxy(GEngine->WireframeMaterial ? GEngine->WireframeMaterial->GetRenderProxy() : NULL, FLinearColor(0, 0.5f, 1.f));
                                                                                                 ^
C:\UE_5.7\Engine\Source\Runtime\Engine\Public\Materials\MaterialRenderProxy.h(322,1): note: could be 'FColoredMaterialRenderProxy::FColoredMaterialRenderProxy(const FColoredMaterialRenderProxy &)'
};
^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(125,84): note: 'FColoredMaterialRenderProxy::FColoredMaterialRenderProxy(const FColoredMaterialRenderProxy &)': cannot convert argument 1 from 'FLinearColor' to 'const FColoredMaterialRenderProxy &'
                FMaterialRenderProxy* WireframeMaterialInstance = new FColoredMaterialRenderProxy(GEngine->WireframeMaterial ? GEngine->WireframeMaterial->GetRenderProxy() : NULL, FLinearColor(0, 0.5f, 1.f));
                                                                                                 ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(125,179): note: Reason: cannot convert from 'FLinearColor' to 'const FColoredMaterialRenderProxy'
                FMaterialRenderProxy* WireframeMaterialInstance = new FColoredMaterialRenderProxy(GEngine->WireframeMaterial ? GEngine->WireframeMaterial->GetRenderProxy() : NULL, FLinearColor(0, 0.5f, 1.f));
                                                                                                                                                                                                ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(125,179): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(125,84): note: while trying to match the argument list '(FLinearColor)'
                FMaterialRenderProxy* WireframeMaterialInstance = new FColoredMaterialRenderProxy(GEngine->WireframeMaterial ? GEngine->WireframeMaterial->GetRenderProxy() : NULL, FLinearColor(0, 0.5f, 1.f));
                                                                                                 ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(186,7): error C2027: use of undefined type 'FSceneViewFamily'
                if (ViewFamily.FrameNumber != LastFrameNumber)
                    ^
C:\UE_5.7\Engine\Source\Runtime\Engine\Public\SceneInterface.h(69,7): note: see declaration of 'FSceneViewFamily'
class FSceneViewFamily;
      ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(191,22): error C2027: use of undefined type 'FSceneViewFamily'
                        LastFrameNumber = ViewFamily.FrameNumber;
                                          ^
C:\UE_5.7\Engine\Source\Runtime\Engine\Public\SceneInterface.h(69,7): note: see declaration of 'FSceneViewFamily'
class FSceneViewFamily;
      ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(236,24): error C2027: use of undefined type 'UMaterialInstanceDynamic'
                                                        MaterialProxy = material->GetRenderProxy();
                                                                        ^
C:\UE_5.7\Engine\Source\Runtime\Engine\Public\SceneManagement.h(56,7): note: see declaration of 'UMaterialInstanceDynamic'
class UMaterialInstanceDynamic;
      ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(331,26): error C2027: use of undefined type 'UMaterialInstanceDynamic'
                                auto MaterialProxy = material->GetRenderProxy();
                                                     ^
C:\UE_5.7\Engine\Source\Runtime\Engine\Public\SceneManagement.h(56,7): note: see declaration of 'UMaterialInstanceDynamic'
class UMaterialInstanceDynamic;
      ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(337,37): error C3536: 'MaterialProxy': cannot be used before it is initialized
                                MeshBatch.MaterialRenderProxy = MaterialProxy;
                                                                ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(337,37): error C2440: '=': cannot convert from 'int' to 'const FMaterialRenderProxy *'
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(337,37): note: Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or parenthesized function-style cast
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(356,13): warning C4996: 'FRayTracingInstanceCollector::AddRayTracingInstance': Please specify ViewIndex. - Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
                        Collector.AddRayTracingInstance(RayTracingInstance);
                                 ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(557,40): error C2027: use of undefined type 'UMaterialInstanceDynamic'
                                if ((DynamicMaterial != nullptr && DynamicMaterial->Parent != OverrideMaterials[ElementIndex]) || OverrideMaterials[ElementIndex] == nullptr)
                                                                   ^
C:\UE_5.7\Engine\Source\Runtime\Engine\Public\SceneManagement.h(56,7): note: see declaration of 'UMaterialInstanceDynamic'
class UMaterialInstanceDynamic;
      ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(605,16): error C2665: 'TArray<UMaterialInterface *,FDefaultAllocator>::Add': no overloaded function could convert all the argument types
                        OutMaterials.Add(material);
                                    ^
C:\UE_5.7\Engine\Source\Runtime\Core\Public\Containers\Array.h(2709,42): note: could be 'int TArray<UMaterialInterface *,FDefaultAllocator>::Add(UMaterialInterface *const &)'
        UE_NODEBUG UE_FORCEINLINE_HINT SizeType Add(const ElementType& Item)
                                                ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(605,16): note: 'int TArray<UMaterialInterface *,FDefaultAllocator>::Add(UMaterialInterface *const &)': cannot convert argument 1 from 'UMaterialInstanceDynamic *' to 'UMaterialInterface *const &'
                        OutMaterials.Add(material);
                                    ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(605,21): note: Reason: cannot convert from 'UMaterialInstanceDynamic *' to 'UMaterialInterface *const '
                        OutMaterials.Add(material);
                                         ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(605,21): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
C:\UE_5.7\Engine\Source\Runtime\Core\Public\Containers\Array.h(2696,42): note: or       'int TArray<UMaterialInterface *,FDefaultAllocator>::Add(UMaterialInterface *&&)'
        UE_NODEBUG UE_FORCEINLINE_HINT SizeType Add(ElementType&& Item)
                                                ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(605,16): note: 'int TArray<UMaterialInterface *,FDefaultAllocator>::Add(UMaterialInterface *&&)': cannot convert argument 1 from 'UMaterialInstanceDynamic *' to 'UMaterialInterface *&&'
                        OutMaterials.Add(material);
                                    ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(605,21): note: Reason: cannot convert from 'UMaterialInstanceDynamic *' to 'UMaterialInterface *'
                        OutMaterials.Add(material);
                                         ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(605,21): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(605,16): note: while trying to match the argument list '(UMaterialInstanceDynamic *)'
                        OutMaterials.Add(material);
                                    ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(620,16): error C2665: 'TArray<UMaterialInterface *,FDefaultAllocator>::Add': no overloaded function could convert all the argument types
                        OutMaterials.Add(material);
                                    ^
C:\UE_5.7\Engine\Source\Runtime\Core\Public\Containers\Array.h(2709,42): note: could be 'int TArray<UMaterialInterface *,FDefaultAllocator>::Add(UMaterialInterface *const &)'
        UE_NODEBUG UE_FORCEINLINE_HINT SizeType Add(const ElementType& Item)
                                                ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(620,16): note: 'int TArray<UMaterialInterface *,FDefaultAllocator>::Add(UMaterialInterface *const &)': cannot convert argument 1 from 'UMaterialInstanceDynamic *' to 'UMaterialInterface *const &'
                        OutMaterials.Add(material);
                                    ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(620,21): note: Reason: cannot convert from 'UMaterialInstanceDynamic *' to 'UMaterialInterface *const '
                        OutMaterials.Add(material);
                                         ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(620,21): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
C:\UE_5.7\Engine\Source\Runtime\Core\Public\Containers\Array.h(2696,42): note: or       'int TArray<UMaterialInterface *,FDefaultAllocator>::Add(UMaterialInterface *&&)'
        UE_NODEBUG UE_FORCEINLINE_HINT SizeType Add(ElementType&& Item)
                                                ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(620,16): note: 'int TArray<UMaterialInterface *,FDefaultAllocator>::Add(UMaterialInterface *&&)': cannot convert argument 1 from 'UMaterialInstanceDynamic *' to 'UMaterialInterface *&&'
                        OutMaterials.Add(material);
                                    ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(620,21): note: Reason: cannot convert from 'UMaterialInstanceDynamic *' to 'UMaterialInterface *'
                        OutMaterials.Add(material);
                                         ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(620,21): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(620,16): note: while trying to match the argument list '(UMaterialInstanceDynamic *)'
                        OutMaterials.Add(material);
                                    ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(745,31): error C2027: use of undefined type 'UMaterial'
                                tmp_material = UMaterial::GetDefaultMaterial(MD_Surface);
                                                          ^
C:\UE_5.7\Engine\Source\Runtime\Engine\Public\MaterialShared.h(68,7): note: see declaration of 'UMaterial'
class UMaterial;
      ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(745,31): error C3861: 'GetDefaultMaterial': identifier not found
                                tmp_material = UMaterial::GetDefaultMaterial(MD_Surface);
                                                          ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(747,67): error C2027: use of undefined type 'UMaterialInstanceDynamic'
                        UMaterialInstanceDynamic* Material = UMaterialInstanceDynamic::Create(tmp_material, this);
                                                                                       ^
C:\UE_5.7\Engine\Source\Runtime\Engine\Public\SceneManagement.h(56,7): note: see declaration of 'UMaterialInstanceDynamic'
class UMaterialInstanceDynamic;
      ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(747,67): error C3861: 'Create': identifier not found
                        UMaterialInstanceDynamic* Material = UMaterialInstanceDynamic::Create(tmp_material, this);
                                                                                       ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(748,4): error C2027: use of undefined type 'UMaterialInstanceDynamic'
                        Material->SetScalarParameterValue(FName(TEXT("FurLength")), FMath::Max(FurLength, 0.001f));
                        ^
C:\UE_5.7\Engine\Source\Runtime\Engine\Public\SceneManagement.h(56,7): note: see declaration of 'UMaterialInstanceDynamic'
class UMaterialInstanceDynamic;
      ^
E:\Lataukset\Gfur57\HostProject\Plugins\GFur\Source\GFur\Private\FurComponent.cpp(775,4): error C2027: use of undefined type 'UMaterialInstanceDynamic'
                        mat->RemoveFromRoot();
                        ^
C:\UE_5.7\Engine\Source\Runtime\Engine\Public\SceneManagement.h(56,7): note: see declaration of 'UMaterialInstanceDynamic'
class UMaterialInstanceDynamic;

**Comment by jalakarp** [comment]
> I had already updated for ue5.7 in this commit [c8cc674](https://github.com/GiM-GamesInMotion/gFurPro/commit/c8cc67440d250c3d9569b6177785adef2643591b) And is in sync in this pr

Does not compile with UE 5.7.3 build tool? Did you try to build with 5.7.3?

**Comment by jalakarp** [comment]
> > I had already updated for ue5.7 in this commit [c8cc674](https://github.com/GiM-GamesInMotion/gFurPro/commit/c8cc67440d250c3d9569b6177785adef2643591b) And is in sync in this pr
> 
> Does not compile with UE 5.7.3 build tool? Did you try to build with 5.7.3?

Fixed by having these includes in 

**FurMorphObject.cpp:**

```
  #include "FurMorphObject.h"
  #include "CoreMinimal.h"
  #include "RenderResource.h"
  #include "RHI.h"
  #include "RHIDefinitions.h"
  #include "RHIResources.h"
  #include "RHICommandList.h"
  #include "FurSkinData.h"
  #include "Rendering/SkeletalMeshRenderData.h"
  #include "Runtime/Engine/Private/SkeletalRenderGPUSkin.h"
  #include "Components/SkinnedMeshComponent.h"
  #include "Animation/MorphTarget.h"
  #include "ShaderParameterUtils.h"
```

**FurComponent.cpp:**

```
#include "FurComponent.h"
#include "GFur.h"
#include "FurSplines.h"
#include "FurData.h"
#include "FurMorphObject.h"
#include "Engine/Engine.h"
#include "PhysicsEngine/BodySetup.h"
#include "DynamicMeshBuilder.h"
#include "GPUSkinVertexFactory.h"
#include "Rendering/SkeletalMeshRenderData.h"
#include "Materials/MaterialRenderProxy.h"
#include "MaterialDomain.h"
#include "MaterialShared.h"
#include "Engine/SkeletalMesh.h"
#include "SceneInterface.h"
#include "Engine/SkinnedAssetCommon.h"
#include "Components/SkinnedMeshComponent.h"
#include "Components/SkeletalMeshComponent.h"
#include "SceneView.h"
#include "PrimitiveSceneProxy.h"
#include "RendererInterface.h"
#include "Engine/CollisionProfile.h"
#include "Runtime/Launch/Resources/Version.h"
#include "ShaderParameterUtils.h"
#include "FurSkinData.h"
#include "FurStaticData.h"
#include "SkeletalRenderPublic.h"
#include "Materials/Material.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "Materials/MaterialInterface.h"
```

**Finally FurData.cpp**

```
#include "FurData.h"
#include "Runtime/Launch/Resources/Version.h"
#include "FurComponent.h
```"

**Comment by millionart** [comment]
5.7.4 BUILD FAILED
